### ISSUE TITLE
Can't calibrate trackers with controls.

### ISSUE THREAD

**Issue by michaeljyang** [Megasteakman/MegaMocapVR#43]
Hi,

I figured to set up all the inputs and trackers, but when I entered play mode, the model would move automatically. I though it should stay at a T-pose and let me calibrate it myself. How can I manage to do that?

https://github.com/Megasteakman/MegaMocapVR/assets/41892892/23eb94e1-8805-4b77-aca8-2a66d6c0e8bc

I ignored this problem and continued. As you can see, the trackers move good, but I could not calibrate with the index controllers, which I thought it should be using the trigger on both controllers. My inputs are usable, you can see the model move with the thumbstick. How can I calibrate trackers to the model with the controls？

Another problems was my position wasn't automatically assigned to the model. So I needed to walk over (which made it hard to see the computer screen), or use the controllers to move the model to me (which mode the unreal camera not centered). How can I fix this problem?

https://github.com/Megasteakman/MegaMocapVR/assets/41892892/ccda2665-76da-462e-9c64-09110bb5ee9b

https://github.com/Megasteakman/MegaMocapVR/assets/41892892/345a43ae-9328-4290-a461-8fa04399f17c

I tried to move to the correct position, with the editor widget and finally I got it working, but it was so hard to do with a wireless mouse and controllers in my hand. 

https://github.com/Megasteakman/MegaMocapVR/assets/41892892/af8283b3-7b46-47c0-9476-b1734784c9a3

I used this system last year and it worked, but somehow I must have done something wrong. Please help me out on how to fix these problems. I really appreciate your work. Thanks again.

**Comment by michaeljyang** [comment]
Another question is after using a mouse clicking the preview screen to make the controller inputs work, how can i get back to using the editor widget?

**Comment by michaeljyang** [comment]
And maybe one more thing that I haven't got to yet, is the index controllers don't seem to pass the finger movement to the model

**Comment by Megasteakman** [comment]
There is a bool on the mocap actor labeled something along the lines of 'Arm Calibration Assistance' which you can turn off.  In my findings, this helps you get more consistant arm placement at the cost of complete accuracy (when I am mocapping actors, they often find it hard to line up the arm, so its really proved useful there).

When a scene locator BP is in the level, your VR center will snap to that.  If you want to rotate the play space so that you can see the scene better, you can change the public variable on the player pawn labeled something like 'rorate when calibrating.'  Otherwise, you can use the editor utilty widget to rotate the play space (I typically Alt Tab out of UE to get mouse control back).

Unfortunately, in the 5.2 release (what the main branch is) I had to remove SteamVR because Unreal deprecated it.  This unfortunately also removed the index finger tracking, and I don't see any way to get it back with OpenXR, although if anyone could help with that I would appreciate it!

**Comment by michaeljyang** [comment]
Ok Thanks a lot!
